// CHLOE MATH 2.3 — Elite Problem Bank 2.0 확장분 (Phase 3 STEP 9/10, PART 12-15).
// 전량 본 프로젝트 원저작 신규 창작 (PART 42: 외부 교재·학원·시험 문제 복제 금지).
// 모든 문제: evidenceMap(PART 19) + noveltySignature(PART 13) 선언 — validateEliteBank가
// 유사 복제(같은 모드에서 동일 reasoning move × 구조 패턴)를 기계 거부한다.
// OPEN_ENDED(PART 15-17): 결정적 검증(정답 판별) + 문제별 rubric + 근거 후속 — 자유서술
// 불투명 채점 없음 (openended23.ts의 설명 가능한 규칙 채점).
import type { EliteProblem } from './eliteBank22.ts';

export const ELITE_BANK_EXT: EliteProblem[] = [
  // ═════════════════════════ STANDARD (심화 정형) ═════════════════════════
  {
    id: 'E.SA.001',
    mode: 'STANDARD',
    difficulty: 4,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.SIGN.02', 'M1.NUM.POW.01', 'M1.NUM.ABS.01'],
    noveltyScore: 0.35,
    reasoningValue: 0.45,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['novelTransfer', 'generalization', 'reverseReasoning', 'explanation'] },
    noveltySignature: { representationType: '복합 수식', requiredSkillCombination: ['M1.NUM.SIGN.02', 'M1.NUM.POW.01', 'M1.NUM.ABS.01'], dominantReasoningMove: 'multi-rule-execution', structuralPattern: '거듭제곱+나눗셈+절댓값 혼합 계산', solutionFamily: ['order-of-operations'] },
    stem: '다음을 계산하세요.\n(−2)⁴ + (−3)³ ÷ 9 − |−5|',
    choices: [{ text: '8' }, { text: '24', eliteTag: 'CARELESS' }, { text: '−8', eliteTag: 'REPRESENTATION' }, { text: '14' }],
    answerIndex: 0,
    hints: {
      A: '세 부분(거듭제곱, 나눗셈, 절댓값)이 각각 몇인지부터 관찰해요.',
      B: '(−2)⁴, (−3)³÷9, |−5|를 각각 따로 적어 보세요.',
      C: '(−2)⁴ = 16, (−3)³ = −27이고 −27÷9 = −3이에요.',
      D: '16 + (−3) − 5를 계산하면 끝이에요.',
    },
    solution: '(−2)⁴ = 16, (−3)³ ÷ 9 = −27 ÷ 9 = −3, |−5| = 5. 따라서 16 + (−3) − 5 = 8.',
    followUps: [],
    estimatedSec: 120,
  },
  {
    id: 'E.SA.002',
    mode: 'STANDARD',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.EQ.BOTH.01', 'M1.ALG.EXP.02'],
    noveltyScore: 0.3,
    reasoningValue: 0.45,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['novelTransfer', 'generalization', 'reverseReasoning', 'explanation'] },
    noveltySignature: { representationType: '방정식', requiredSkillCombination: ['M1.ALG.EQ.BOTH.01', 'M1.ALG.EXP.02'], dominantReasoningMove: 'multi-rule-execution', structuralPattern: '이중 괄호 전개 후 양변 이항', solutionFamily: ['expand-then-isolate'] },
    stem: '방정식을 푸세요.\n4(x − 1) − (x − 5) = 2x + 7',
    choices: [{ text: 'x = 6' }, { text: 'x = 16', eliteTag: 'CARELESS' }, { text: 'x = 3' }, { text: 'x = 5' }],
    answerIndex: 0,
    hints: {
      A: '괄호가 두 개 — 특히 앞의 −부호가 있는 괄호를 주의 깊게 보세요.',
      B: '−(x − 5)는 −x + 5로 전개돼요. 좌변 전체를 정리해 보세요.',
      C: '좌변 = 4x − 4 − x + 5 = 3x + 1.',
      D: '3x + 1 = 2x + 7에서 x를 한쪽으로 모으면?',
    },
    solution: '좌변: 4x − 4 − x + 5 = 3x + 1. 3x + 1 = 2x + 7 → x = 6.',
    followUps: [],
    estimatedSec: 110,
  },
  {
    id: 'E.SA.003',
    mode: 'STANDARD',
    difficulty: 4,
    domain: 'FUN',
    requiredSkills: ['M1.FUN.PROP.03', 'M1.FUN.PROP.02'],
    noveltyScore: 0.3,
    reasoningValue: 0.4,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [], exclusionDimensions: ['novelTransfer', 'generalization', 'reverseReasoning', 'explanation', 'flexibility'] },
    noveltySignature: { representationType: '조건 문장', requiredSkillCombination: ['M1.FUN.PROP.03', 'M1.FUN.PROP.02'], dominantReasoningMove: 'multi-rule-execution', structuralPattern: '반비례 상수 결정 후 역방향 조회', solutionFamily: ['constant-first'] },
    stem: 'y가 x에 반비례하고, x = 4일 때 y = 9입니다. y = 6일 때 x의 값은?',
    choices: [{ text: '6' }, { text: '13.5', eliteTag: 'REPRESENTATION' }, { text: '24' }, { text: '9' }],
    answerIndex: 0,
    hints: {
      A: '반비례에서 변하지 않는 것이 무엇인지 떠올려요.',
      B: 'x × y가 항상 일정해요. 먼저 그 값을 구하세요.',
      C: 'a = 4 × 9 = 36.',
      D: 'x × 6 = 36이 되는 x는?',
    },
    solution: 'a = xy = 4 × 9 = 36. y = 6일 때 x = 36 ÷ 6 = 6.',
    followUps: [],
    estimatedSec: 100,
  },
  {
    id: 'E.SA.004',
    mode: 'STANDARD',
    difficulty: 4,
    domain: 'STA',
    requiredSkills: ['M1.STA.AVG.02', 'M1.STA.AVG.01'],
    noveltyScore: 0.35,
    reasoningValue: 0.45,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.3 }], exclusionDimensions: ['novelTransfer', 'generalization', 'reverseReasoning', 'flexibility'] },
    noveltySignature: { representationType: '문장', requiredSkillCombination: ['M1.STA.AVG.02', 'M1.STA.AVG.01'], dominantReasoningMove: 'multi-rule-execution', structuralPattern: '평균 갱신에서 신규 항 역산', solutionFamily: ['total-difference'] },
    stem: '채림이는 다섯 번의 시험에서 평균 82점을 받았습니다. 여섯 번째 시험을 본 뒤 전체 평균이 84점이 되었다면, 여섯 번째 시험 점수는?',
    choices: [{ text: '94점' }, { text: '86점', eliteTag: 'STRATEGY' }, { text: '92점' }, { text: '96점' }],
    answerIndex: 0,
    hints: {
      A: '평균이 아니라 "총합"으로 생각을 바꿔 보세요.',
      B: '다섯 번의 총합과 여섯 번의 총합을 각각 식으로 적어요.',
      C: '5회 총합 = 82×5 = 410, 6회 총합 = 84×6 = 504.',
      D: '여섯 번째 점수 = 504 − 410.',
    },
    solution: '6회 총합 504 − 5회 총합 410 = 94점. (평균이 2점 오르려면 새 점수가 새 평균보다 (기존 횟수)×2 = 10점 높아야 한다는 구조: 84+10 = 94로도 검산 가능.)',
    followUps: [],
    estimatedSec: 130,
  },
  {
    id: 'E.SA.005',
    mode: 'STANDARD',
    difficulty: 5,
    domain: 'GEO',
    requiredSkills: ['M1.GEO.POLY.01', 'M1.GEO.POLY.02'],
    noveltyScore: 0.35,
    reasoningValue: 0.5,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['novelTransfer', 'reverseReasoning', 'explanation', 'flexibility'] },
    noveltySignature: { representationType: '조건 문장', requiredSkillCombination: ['M1.GEO.POLY.01', 'M1.GEO.POLY.02'], dominantReasoningMove: 'multi-rule-execution', structuralPattern: '내각합→n→대각선 2단 연쇄', solutionFamily: ['chain-computation'] },
    stem: '내각의 크기의 합이 1440°인 다각형의 대각선의 개수는?',
    choices: [{ text: '35개' }, { text: '45개', eliteTag: 'STRATEGY' }, { text: '27개' }, { text: '20개' }],
    answerIndex: 0,
    hints: {
      A: '두 단계 문제예요 — 먼저 무엇을 구해야 할까요?',
      B: '내각합 공식 180(n−2) = 1440에서 n부터.',
      C: 'n − 2 = 8 → n = 10.',
      D: '십각형의 대각선: 10 × (10−3) ÷ 2.',
    },
    solution: '180(n−2) = 1440 → n = 10. 대각선 = 10×7÷2 = 35개.',
    followUps: [],
    estimatedSec: 140,
  },

  // ═════════════════════════ APPLICATION (표현 번역) ═════════════════════════
  {
    id: 'E.AP.002',
    mode: 'APPLICATION',
    difficulty: 3,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.SIGN.01', 'M1.NUM.ABS.01'],
    noveltyScore: 0.5,
    reasoningValue: 0.55,
    evidenceMap: { primaryDimension: 'representation', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'justification', 'flexibility'] },
    noveltySignature: { representationType: '수직선', requiredSkillCombination: ['M1.NUM.SIGN.01', 'M1.NUM.ABS.01'], dominantReasoningMove: 'multi-rep-translation', structuralPattern: '수직선 거리의 절댓값 표현', solutionFamily: ['distance-as-absolute'] },
    stem: '수직선 위에 지하 주차장 입구 A(−7)와 엘리베이터 B(5)가 있습니다. A에서 B까지의 거리는?',
    choices: [{ text: '12' }, { text: '2', eliteTag: 'REPRESENTATION' }, { text: '−12' }, { text: '35' }],
    answerIndex: 0,
    hints: {
      A: '수직선을 그려 두 점을 찍어 보세요.',
      B: '거리 = 두 수의 차의 절댓값으로 표현할 수 있어요.',
      C: '|5 − (−7)|을 계산해요.',
      D: '5 − (−7) = 12.',
    },
    solution: '거리 = |5 − (−7)| = |12| = 12. (0을 기준으로 7 + 5로 세어도 같다.)',
    followUps: [
      {
        id: 'E.AP.002.f1',
        dimension: 'representation',
        prompt: '두 점 a, b 사이의 거리를 항상 옳게 나타내는 식은?',
        choices: [{ text: '|a − b|' }, { text: 'a − b', eliteTag: 'REPRESENTATION' }, { text: 'a + b' }, { text: '|a| − |b|', eliteTag: 'REPRESENTATION' }],
        answerIndex: 0,
        note: 'a−b는 부호가 남고, |a|−|b|는 (−7, 5)에서 2가 되어 거리가 아니다. 차의 절댓값만이 항상 거리다.',
      },
    ],
    estimatedSec: 90,
  },
  {
    id: 'E.AP.003',
    mode: 'APPLICATION',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.EQ.03', 'M1.ALG.EQ.BOTH.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.6,
    evidenceMap: { primaryDimension: 'representation', secondaryDimensions: [{ dimension: 'integration', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'justification', 'flexibility'] },
    noveltySignature: { representationType: '실생활 문장', requiredSkillCombination: ['M1.ALG.EQ.03', 'M1.ALG.EQ.BOTH.01'], dominantReasoningMove: 'multi-rep-translation', structuralPattern: '두 요금제 손익분기 방정식화', solutionFamily: ['equate-two-expressions'] },
    stem: 'A요금제는 기본요금 3000원에 1분당 50원, B요금제는 기본요금 없이 1분당 110원입니다. 한 달 통화가 몇 분일 때 두 요금제의 요금이 같아질까요?',
    choices: [{ text: '50분' }, { text: '30분' }, { text: '27분', eliteTag: 'STRATEGY' }, { text: '60분' }],
    answerIndex: 0,
    hints: {
      A: '통화 시간을 문자로 놓고 각 요금제를 식으로 옮겨요.',
      B: 'A: 3000 + 50m, B: 110m.',
      C: '"같아진다" = 두 식을 등호로 잇기.',
      D: '3000 + 50m = 110m → 60m = 3000.',
    },
    solution: '3000 + 50m = 110m → 3000 = 60m → m = 50분.',
    followUps: [],
    estimatedSec: 150,
  },
  {
    id: 'E.AP.004',
    mode: 'APPLICATION',
    difficulty: 4,
    domain: 'FUN',
    requiredSkills: ['M1.FUN.PROP.01', 'M1.FUN.PROP.04'],
    noveltyScore: 0.5,
    reasoningValue: 0.55,
    evidenceMap: { primaryDimension: 'representation', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'justification', 'flexibility'] },
    noveltySignature: { representationType: '실생활 문장', requiredSkillCombination: ['M1.FUN.PROP.01', 'M1.FUN.PROP.04'], dominantReasoningMove: 'multi-rep-translation', structuralPattern: '단위율 결정 후 정비례 확장', solutionFamily: ['unit-rate'] },
    stem: '빈 수조에 물을 일정한 속도로 받고 있습니다. 4분 동안 18L가 채워졌다면, 30분 동안 받으면 몇 L가 채워질까요?',
    choices: [{ text: '135L' }, { text: '120L' }, { text: '72L', eliteTag: 'STRATEGY' }, { text: '150L' }],
    answerIndex: 0,
    hints: {
      A: '시간과 물의 양은 어떤 관계일까요?',
      B: 'y = ax 꼴로 놓고 a(1분당 양)부터 구해요.',
      C: 'a = 18 ÷ 4 = 4.5L/분.',
      D: 'y = 4.5 × 30.',
    },
    solution: '정비례 y = 4.5x → x = 30에서 y = 135L.',
    followUps: [],
    estimatedSec: 110,
  },
  {
    id: 'E.AP.005',
    mode: 'APPLICATION',
    difficulty: 3,
    domain: 'STA',
    requiredSkills: ['M1.STA.REL.01', 'M1.STA.REL.02'],
    noveltyScore: 0.45,
    reasoningValue: 0.5,
    evidenceMap: { primaryDimension: 'representation', secondaryDimensions: [], exclusionDimensions: ['generalization', 'reverseReasoning', 'justification', 'flexibility', 'novelTransfer'] },
    noveltySignature: { representationType: '표', requiredSkillCombination: ['M1.STA.REL.01', 'M1.STA.REL.02'], dominantReasoningMove: 'multi-rep-translation', structuralPattern: '상대도수→도수 역번역', solutionFamily: ['ratio-inversion'] },
    stem: '전체 학생 40명을 조사한 표에서, 어느 계급의 상대도수가 0.35입니다. 이 계급의 도수(학생 수)는?',
    choices: [{ text: '14명' }, { text: '11명' }, { text: '26명', eliteTag: 'STRATEGY' }, { text: '35명', eliteTag: 'REPRESENTATION' }],
    answerIndex: 0,
    hints: {
      A: '상대도수의 정의를 식으로 적어 보세요.',
      B: '상대도수 = 도수 ÷ 전체.',
      C: '0.35 = 도수 ÷ 40.',
      D: '도수 = 0.35 × 40.',
    },
    solution: '도수 = 상대도수 × 전체 = 0.35 × 40 = 14명.',
    followUps: [],
    estimatedSec: 80,
  },

  // ═════════════════════════ MULTI_SKILL ═════════════════════════
  {
    id: 'E.MS.003',
    mode: 'MULTI_SKILL',
    difficulty: 4,
    domain: 'FUN',
    requiredSkills: ['M1.FUN.AREA.01', 'M1.FUN.COORD.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.65,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.4 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'explanation'] },
    noveltySignature: { representationType: '좌표', requiredSkillCombination: ['M1.FUN.AREA.01', 'M1.FUN.COORD.01'], dominantReasoningMove: 'concept-combination', structuralPattern: '좌표 세 점의 직각삼각형 넓이', solutionFamily: ['coordinate-lengths'] },
    stem: '좌표평면 위의 세 점 A(−3, 4), B(5, 4), C(5, −2)를 꼭짓점으로 하는 삼각형 ABC의 넓이는?',
    choices: [{ text: '24' }, { text: '48', eliteTag: 'CARELESS' }, { text: '14', eliteTag: 'INTEGRATION' }, { text: '12' }],
    answerIndex: 0,
    hints: {
      A: '세 점을 좌표평면에 찍어 보세요 — 특별한 모양이 보여요.',
      B: 'AB는 가로선, BC는 세로선 — 길이를 좌표의 차로 구해요.',
      C: 'AB = 5 − (−3) = 8, BC = 4 − (−2) = 6.',
      D: '직각삼각형: 8 × 6 ÷ 2.',
    },
    solution: 'AB = 8(가로), BC = 6(세로), ∠B = 90°. 넓이 = 8×6÷2 = 24.',
    followUps: [],
    estimatedSec: 160,
  },
  {
    id: 'E.MS.004',
    mode: 'MULTI_SKILL',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.VAL.02', 'M1.NUM.POW.01'],
    noveltyScore: 0.5,
    reasoningValue: 0.6,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'explanation', 'novelTransfer'] },
    noveltySignature: { representationType: '식', requiredSkillCombination: ['M1.ALG.VAL.02', 'M1.NUM.POW.01'], dominantReasoningMove: 'concept-combination', structuralPattern: '음수 대입 + 부호 있는 거듭제곱 결합', solutionFamily: ['careful-substitution'] },
    stem: 'x = −2일 때, 다음 식의 값을 구하세요.\nx² − 3x + (−x)³',
    choices: [{ text: '18' }, { text: '6', eliteTag: 'CARELESS' }, { text: '2', eliteTag: 'REPRESENTATION' }, { text: '−10' }],
    answerIndex: 0,
    hints: {
      A: '세 항을 하나씩 따로 계산해요 — 괄호를 씌워 대입!',
      B: 'x² = (−2)², −3x = −3×(−2), (−x)³ = (2)³.',
      C: '4, +6, 그리고 (−x) = 2이므로 2³ = 8.',
      D: '4 + 6 + 8.',
    },
    solution: 'x² = 4, −3x = 6, (−x)³ = 2³ = 8. 합계 18. (−x)³을 −8로 계산하면 함정에 빠진다 — x가 음수이므로 −x는 양수.',
    followUps: [],
    estimatedSec: 150,
  },
  {
    id: 'E.MS.005',
    mode: 'MULTI_SKILL',
    difficulty: 5,
    domain: 'STA',
    requiredSkills: ['M1.STA.AVG.02', 'M1.ALG.EQ.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.65,
    evidenceMap: { primaryDimension: 'integration', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'flexibility'] },
    noveltySignature: { representationType: '문장', requiredSkillCombination: ['M1.STA.AVG.02', 'M1.ALG.EQ.01'], dominantReasoningMove: 'concept-combination', structuralPattern: '미지수 포함 자료의 평균 방정식화', solutionFamily: ['equation-setup'] },
    stem: '세 수 a, a + 4, 11의 평균이 9일 때, a의 값은?',
    choices: [{ text: '6' }, { text: '9', eliteTag: 'STRATEGY' }, { text: '4' }, { text: '12', eliteTag: 'CARELESS' }],
    answerIndex: 0,
    hints: {
      A: '평균의 정의로 식을 세워요.',
      B: '(a + a+4 + 11) ÷ 3 = 9.',
      C: '2a + 15 = 27.',
      D: '2a = 12.',
    },
    solution: '(2a + 15)/3 = 9 → 2a + 15 = 27 → a = 6.',
    followUps: [],
    estimatedSec: 130,
  },

  // ═════════════════════════ NON_ROUTINE ═════════════════════════
  {
    id: 'E.NR.004',
    mode: 'NON_ROUTINE',
    difficulty: 4,
    domain: 'GEO',
    requiredSkills: ['M1.GEO.POLY.01', 'M1.GEO.ANG.01'],
    noveltyScore: 0.85,
    reasoningValue: 0.85,
    evidenceMap: { primaryDimension: 'strategySelection', secondaryDimensions: [{ dimension: 'novelTransfer', evidenceFraction: 0.5 }], exclusionDimensions: ['reverseReasoning', 'explanation', 'flexibility'] },
    noveltySignature: { representationType: '도형', requiredSkillCombination: ['M1.GEO.POLY.01', 'M1.GEO.ANG.01'], dominantReasoningMove: 'decomposition-strategy', structuralPattern: '별 모양 꼭지각의 합 분해', solutionFamily: ['triangle-decomposition', 'angle-sum'] },
    stem: '정오각형의 각 변을 연장해 만든 별 모양(★)에서, 뾰족한 꼭지각 5개의 크기의 합은?',
    choices: [{ text: '180°' }, { text: '360°', eliteTag: 'STRATEGY' }, { text: '540°', eliteTag: 'REPRESENTATION' }, { text: '900°' }],
    answerIndex: 0,
    hints: {
      A: '한 꼭지각만 떼어 보면 어떤 도형의 일부일까요?',
      B: '꼭지 하나는 삼각형의 꼭대기각 — 밑의 두 각은 오각형 밖의 각과 연결돼요.',
      C: '정오각형 한 내각 108° → 이웃 외각 72°. 꼭지 삼각형의 두 밑각이 각각 72°.',
      D: '꼭지각 하나 = 180 − 72 − 72 = 36°. 다섯 개면?',
    },
    solution: '별의 꼭지 하나는 밑각이 72°, 72°인 삼각형의 꼭대기각 = 36°. 5개 합 = 180°. (오각형 내각합 540°와 혼동하지 않기.)',
    followUps: [
      {
        id: 'E.NR.004.f1',
        dimension: 'generalization',
        prompt: '정n각형(n≥5)으로 같은 별을 만들면 꼭지각의 합은 어떻게 될까요?',
        choices: [{ text: '항상 180°... 는 아니고, 180(n−4)°가 된다' }, { text: '항상 180°' }, { text: '항상 360°' }, { text: 'n × 36°' }],
        answerIndex: 0,
        note: '꼭지각 하나 = 180 − 2×(360/n) = 180(n−4)/n. n개 합 = 180(n−4)°. n=5에서 180°.',
      },
    ],
    estimatedSec: 240,
  },
  {
    id: 'E.NR.005',
    mode: 'NON_ROUTINE',
    difficulty: 3,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.SIGN.01', 'M1.NUM.SIGN.02'],
    noveltyScore: 0.8,
    reasoningValue: 0.7,
    evidenceMap: { primaryDimension: 'novelTransfer', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.4 }], exclusionDimensions: ['generalization', 'explanation', 'reverseReasoning'] },
    noveltySignature: { representationType: '기호 퍼즐', requiredSkillCombination: ['M1.NUM.SIGN.01', 'M1.NUM.SIGN.02'], dominantReasoningMove: 'rule-adoption', structuralPattern: '새 연산 기호 정의 적용', solutionFamily: ['definition-substitution'] },
    stem: '새로운 연산 ◇를 다음과 같이 정합니다.\na ◇ b = a × b − (a + b)\n이때 (−2) ◇ 3의 값은?',
    choices: [{ text: '−7' }, { text: '−5', eliteTag: 'CARELESS' }, { text: '1', eliteTag: 'REPRESENTATION' }, { text: '−11' }],
    answerIndex: 0,
    hints: {
      A: '처음 보는 기호지만, 정의가 전부예요 — 정의를 그대로 옮겨 적어요.',
      B: 'a 자리에 −2, b 자리에 3을 괄호째 넣어요.',
      C: '(−2)×3 = −6, (−2)+3 = 1.',
      D: '−6 − 1.',
    },
    solution: '(−2)◇3 = (−2)(3) − ((−2)+3) = −6 − 1 = −7.',
    followUps: [],
    estimatedSec: 130,
  },

  // ═════════════════════════ REVERSE ═════════════════════════
  {
    id: 'E.RV.003',
    mode: 'REVERSE',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.EQ.01', 'M1.ALG.EQ.AX.01'],
    noveltyScore: 0.6,
    reasoningValue: 0.7,
    evidenceMap: { primaryDimension: 'reverseReasoning', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'explanation', 'novelTransfer'] },
    noveltySignature: { representationType: '식', requiredSkillCombination: ['M1.ALG.EQ.01', 'M1.ALG.EQ.AX.01'], dominantReasoningMove: 'reverse-construction', structuralPattern: '해에서 방정식 식별', solutionFamily: ['substitution-check'] },
    stem: '해가 x = −3인 방정식은 어느 것일까요?',
    choices: [{ text: '2x + 5 = −1' }, { text: '3x − 1 = 10' }, { text: '−x + 4 = 1', eliteTag: 'REPRESENTATION' }, { text: '5x = 15', eliteTag: 'CARELESS' }],
    answerIndex: 0,
    hints: {
      A: '거꾸로 문제예요 — 풀지 말고 확인하는 방법도 있어요.',
      B: 'x = −3을 각 식에 대입해 등호가 성립하는지 검사해요.',
      C: '첫 번째: 2(−3) + 5 = −6 + 5 = −1.',
      D: '−1 = −1 성립!',
    },
    solution: '2(−3)+5 = −1 ✓. 나머지는 각각 x = 11/3, x = 3, x = 3이 해이므로 −3이 아니다. (부호 함정: −x+4=1과 5x=15의 해는 +3.)',
    followUps: [
      {
        id: 'E.RV.003.f1',
        dimension: 'reverseReasoning',
        prompt: '해가 x = −3인 새로운 방정식을 직접 만들려면 가장 확실한 방법은?',
        choices: [{ text: 'x = −3에서 시작해 양변에 같은 연산을 쌓아 올린다' }, { text: '아무 방정식이나 쓰고 우변을 −3으로 바꾼다', eliteTag: 'STRATEGY' }, { text: '−3이 들어간 식을 아무거나 쓴다' }, { text: '해가 3인 방정식의 부호를 전부 바꾼다' }],
        answerIndex: 0,
        note: '해에서 거꾸로 구성: x=−3 → 2x=−6 → 2x+5=−1. 만들기와 풀기가 역연산 관계임을 보는 것이 핵심.',
      },
    ],
    estimatedSec: 150,
  },
  {
    id: 'E.RV.004',
    mode: 'REVERSE',
    difficulty: 4,
    domain: 'STA',
    requiredSkills: ['M1.STA.AVG.01', 'M1.STA.AVG.02'],
    noveltyScore: 0.65,
    reasoningValue: 0.7,
    evidenceMap: { primaryDimension: 'reverseReasoning', secondaryDimensions: [{ dimension: 'integration', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'explanation', 'novelTransfer', 'flexibility'] },
    noveltySignature: { representationType: '수 조합', requiredSkillCombination: ['M1.STA.AVG.01', 'M1.STA.AVG.02'], dominantReasoningMove: 'reverse-construction', structuralPattern: '평균 조건을 만족하는 자료 재구성', solutionFamily: ['total-check'] },
    stem: '네 수의 평균이 7이라고 합니다. 다음 중 그 네 수가 될 수 있는 조합은?',
    choices: [{ text: '5, 9, 6, 8' }, { text: '7, 7, 7, 8', eliteTag: 'CARELESS' }, { text: '5, 5, 9, 10' }, { text: '6, 6, 8, 9' }],
    answerIndex: 0,
    hints: {
      A: '평균 조건을 "총합 조건"으로 바꿔 보세요.',
      B: '평균 7 × 4개 = 총합 28이어야 해요.',
      C: '각 조합의 합을 빠르게 검사해요.',
      D: '5+9+6+8 = 28 ✓.',
    },
    solution: '평균 7 ⇔ 총합 28. 5+9+6+8 = 28만 성립 (나머지는 모두 29).',
    followUps: [],
    estimatedSec: 120,
  },
  {
    id: 'E.RV.005',
    mode: 'REVERSE',
    difficulty: 3,
    domain: 'FUN',
    requiredSkills: ['M1.FUN.PROP.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.6,
    evidenceMap: { primaryDimension: 'reverseReasoning', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.3 }], exclusionDimensions: ['generalization', 'explanation', 'novelTransfer', 'flexibility'] },
    noveltySignature: { representationType: '좌표+식', requiredSkillCombination: ['M1.FUN.PROP.01'], dominantReasoningMove: 'reverse-construction', structuralPattern: '지나는 점에서 관계식 역결정', solutionFamily: ['substitution-check'] },
    stem: '그래프가 점 (2, −6)을 지나는 정비례 관계식은?',
    choices: [{ text: 'y = −3x' }, { text: 'y = 3x', eliteTag: 'CARELESS' }, { text: 'y = −2x' }, { text: 'y = −6x' }],
    answerIndex: 0,
    hints: {
      A: '정비례는 y = ax 꼴 — 모르는 것은 a 하나뿐이에요.',
      B: '지나는 점의 x, y를 식에 대입하면 a가 결정돼요.',
      C: '−6 = a × 2.',
      D: 'a = −3.',
    },
    solution: 'y = ax에 (2, −6) 대입 → a = −3 → y = −3x.',
    followUps: [],
    estimatedSec: 90,
  },

  // ═════════════════════════ GENERALIZATION ═════════════════════════
  {
    id: 'E.GN.003',
    mode: 'GENERALIZATION',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.PAT.01', 'M1.ALG.EXP.01'],
    noveltyScore: 0.7,
    reasoningValue: 0.85,
    evidenceMap: { primaryDimension: 'generalization', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.3 }], exclusionDimensions: ['reverseReasoning', 'novelTransfer', 'flexibility'] },
    noveltySignature: { representationType: '상황 그림', requiredSkillCombination: ['M1.ALG.PAT.01', 'M1.ALG.EXP.01'], dominantReasoningMove: 'generalize-pattern', structuralPattern: '테이블 연결의 자리 수 일반항', solutionFamily: ['first-term-anchoring'] },
    stem: '정사각형 테이블 1개에는 4명이 앉을 수 있습니다. 테이블을 한 줄로 n개 이어 붙이면(붙은 변에는 앉지 못함) 앉을 수 있는 사람 수는?',
    choices: [{ text: '2n + 2' }, { text: '4n', eliteTag: 'GENERALIZATION' }, { text: '3n + 1', eliteTag: 'GENERALIZATION' }, { text: 'n + 3', eliteTag: 'GENERALIZATION' }],
    answerIndex: 0,
    hints: {
      A: 'n = 1, 2, 3일 때를 직접 세어 보세요.',
      B: '1개: 4명, 2개: 6명, 3개: 8명 — 어떤 규칙일까요?',
      C: '하나 늘 때마다 2명씩 — 계수는 2. 상수는 n=1로 결정해요.',
      D: '2×1 + □ = 4 → □ = 2.',
    },
    solution: '위아래로 n명씩(2n) + 양 끝 2명 = 2n+2. 함정 보기 셋은 모두 n=1에서 4가 되지만 n=2에서 갈라진다 — 일반화 검산은 두 개 이상의 사례로!',
    followUps: [
      {
        id: 'E.GN.003.f1',
        dimension: 'justification',
        prompt: '4n이 틀렸다는 것을 가장 확실하게 보여주는 방법은?',
        choices: [{ text: 'n=2를 대입하면 8이 나오지만 실제로는 6명이다' }, { text: '식이 너무 단순해 보인다', eliteTag: 'JUSTIFICATION' }, { text: 'n=1에서 4가 나오니 맞는 식이다', eliteTag: 'JUSTIFICATION' }, { text: '계수가 4라서 정사각형과 어울린다' }],
        answerIndex: 0,
        note: '반례 하나(n=2에서 8≠6)가 결정적이다. n=1 통과는 아무것도 보장하지 않는다.',
      },
    ],
    estimatedSec: 200,
  },
  {
    id: 'E.GN.004',
    mode: 'GENERALIZATION',
    difficulty: 4,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.POW.01', 'M1.NUM.SIGN.02'],
    noveltyScore: 0.65,
    reasoningValue: 0.8,
    evidenceMap: { primaryDimension: 'generalization', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.3 }], exclusionDimensions: ['reverseReasoning', 'novelTransfer', 'flexibility'] },
    noveltySignature: { representationType: '수열 합', requiredSkillCombination: ['M1.NUM.POW.01', 'M1.NUM.SIGN.02'], dominantReasoningMove: 'case-split', structuralPattern: '(−1)ⁿ 부분합의 홀짝 규칙', solutionFamily: ['parity-argument', 'pairing'] },
    stem: '(−1)¹ + (−1)² + (−1)³ + ⋯ + (−1)ⁿ 의 값에 대한 설명으로 옳은 것은?',
    choices: [
      { text: 'n이 짝수면 0, 홀수면 −1' },
      { text: '항상 0', eliteTag: 'GENERALIZATION' },
      { text: '항상 −1', eliteTag: 'GENERALIZATION' },
      { text: 'n이 짝수면 1, 홀수면 0' },
    ],
    answerIndex: 0,
    hints: {
      A: 'n = 1, 2, 3, 4일 때 직접 계산해 보세요.',
      B: '−1, 0, −1, 0, … 이 반복돼요. 왜일까요?',
      C: '이웃한 두 항 (−1)+(+1)이 짝을 이뤄 0이 돼요.',
      D: '짝수 n이면 전부 짝지어 0, 홀수면 −1 하나가 남아요.',
    },
    solution: '연속 두 항이 (−1)+(+1)=0으로 소거. n 짝수 → 0, n 홀수 → 마지막 −1이 남아 −1.',
    followUps: [],
    estimatedSec: 170,
  },
  {
    id: 'E.GN.005',
    mode: 'GENERALIZATION',
    difficulty: 5,
    domain: 'GEO',
    requiredSkills: ['M1.GEO.POLY.02', 'M1.GEO.POLY.01'],
    noveltyScore: 0.6,
    reasoningValue: 0.85,
    evidenceMap: { primaryDimension: 'generalization', secondaryDimensions: [{ dimension: 'justification', evidenceFraction: 0.3 }], exclusionDimensions: ['reverseReasoning', 'novelTransfer', 'flexibility'] },
    noveltySignature: { representationType: '도형+식', requiredSkillCombination: ['M1.GEO.POLY.02', 'M1.GEO.POLY.01'], dominantReasoningMove: 'generalize-pattern', structuralPattern: '대각선 개수 공식의 구조 유도', solutionFamily: ['counting-argument'] },
    stem: 'n각형의 한 꼭짓점에서 그을 수 있는 대각선은 (n−3)개입니다. 그렇다면 n각형 전체의 대각선 개수를 나타내는 식은?',
    choices: [
      { text: 'n(n−3)/2' },
      { text: 'n(n−3)', eliteTag: 'GENERALIZATION' },
      { text: 'n(n−1)/2', eliteTag: 'INTEGRATION' },
      { text: '(n−2)(n−3)' },
    ],
    answerIndex: 0,
    hints: {
      A: '모든 꼭짓점에서 (n−3)개씩 그으면 무슨 일이 생길까요?',
      B: '대각선 AB와 BA는 같은 선이에요.',
      C: 'n(n−3)은 각 대각선을 두 번씩 센 것.',
      D: '그래서 2로 나눠요.',
    },
    solution: '꼭짓점 n개 × 각 (n−3)개 = n(n−3), 그러나 각 대각선이 양 끝에서 두 번 세어지므로 ÷2. n(n−3)/2.',
    followUps: [
      {
        id: 'E.GN.005.f1',
        dimension: 'explanation',
        prompt: '"2로 나누는 이유"를 가장 정확히 설명한 것은?',
        choices: [{ text: '한 대각선이 양 끝 꼭짓점에서 한 번씩, 총 두 번 세어지기 때문' }, { text: '다각형이 좌우대칭이기 때문', eliteTag: 'JUSTIFICATION' }, { text: '공식이 그렇게 정해져 있기 때문', eliteTag: 'JUSTIFICATION' }, { text: '넓이를 구할 때도 2로 나누기 때문' }],
        answerIndex: 0,
        note: '중복 계산의 구조(쌍 세기)를 말로 짚는 것 — 공식 암기와 구조 이해를 가르는 지점.',
      },
    ],
    estimatedSec: 210,
  },

  // ═════════════════════════ PROOF ═════════════════════════
  {
    id: 'E.PR.002',
    mode: 'PROOF',
    difficulty: 4,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.SIGN.02'],
    noveltyScore: 0.6,
    reasoningValue: 0.9,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'explanation', evidenceFraction: 0.5 }], exclusionDimensions: ['novelTransfer', 'flexibility', 'reverseReasoning'] },
    noveltySignature: { representationType: '논증 선택', requiredSkillCombination: ['M1.NUM.SIGN.02'], dominantReasoningMove: 'deductive-argument', structuralPattern: '음수×음수 부호 규칙의 근거', solutionFamily: ['distributive-derivation'] },
    stem: '"음수 × 음수 = 양수"의 근거로 수학적으로 가장 타당한 것은?',
    choices: [
      { text: '(−a)×(−b) + (−a)×b = (−a)×(−b+b) = 0이고 (−a)×b = −ab이므로, (−a)×(−b)는 −ab와 더해 0이 되는 수, 즉 ab이다' },
      { text: '음수가 두 번이면 부호가 상쇄된다고 약속했기 때문이다', eliteTag: 'JUSTIFICATION' },
      { text: '(−2)×(−3)=6처럼 여러 예에서 확인되기 때문이다', eliteTag: 'JUSTIFICATION' },
      { text: '계산기가 항상 양수로 답하기 때문이다' },
    ],
    answerIndex: 0,
    hints: {
      A: '"왜"에 대한 답은 규칙 암기·예시 나열보다 강해야 해요.',
      B: '이미 아는 사실(분배법칙, 0의 성질)에서 끌어낼 수 있을까요?',
      C: '(−a) × (−b + b)를 두 가지 방법으로 계산해 비교해요.',
      D: '분배하면 (−a)(−b) + (−ab), 직접 계산하면 (−a)×0 = 0.',
    },
    solution: '분배법칙으로 (−a)(−b) + (−a)(b) = (−a)(−b+b) = 0. (−a)(b) = −ab이므로 (−a)(−b)는 −ab의 덧셈 역원 = ab. 예시 확인이나 "약속"은 이유가 아니라 관찰/규약의 서술이다.',
    followUps: [],
    estimatedSec: 220,
  },
  {
    id: 'E.PR.003',
    mode: 'PROOF',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.EXP.01', 'M1.ALG.PAT.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.9,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'generalization', evidenceFraction: 0.4 }], exclusionDimensions: ['novelTransfer', 'flexibility', 'reverseReasoning'] },
    noveltySignature: { representationType: '논증 선택', requiredSkillCombination: ['M1.ALG.EXP.01', 'M1.ALG.PAT.01'], dominantReasoningMove: 'deductive-argument', structuralPattern: '연속 정수 합의 배수성 증명', solutionFamily: ['symbolic-representation'] },
    stem: '"연속하는 세 정수의 합은 항상 3의 배수다"를 증명하는 것으로 완전한 것은?',
    choices: [
      { text: '가운데 수를 n으로 놓으면 (n−1) + n + (n+1) = 3n — n이 정수이므로 항상 3의 배수' },
      { text: '1+2+3=6, 4+5+6=15, 7+8+9=24가 모두 3의 배수이므로', eliteTag: 'JUSTIFICATION' },
      { text: '세 수를 더하면 항상 홀수가 되는데 홀수 중엔 3의 배수가 많으므로', eliteTag: 'JUSTIFICATION' },
      { text: '연속하는 수는 평균이 가운데 수이므로 대충 3배가 되므로' },
    ],
    answerIndex: 0,
    hints: {
      A: '"항상"을 보이려면 모든 경우를 한 번에 담는 표현이 필요해요.',
      B: '연속하는 세 정수를 문자 하나로 나타내 보세요.',
      C: '가운데를 n으로: n−1, n, n+1.',
      D: '더하면 3n — 문자가 "모든 경우"를 대신해요.',
    },
    solution: '(n−1)+n+(n+1) = 3n. 문자 표현이 무한한 사례를 한 번에 처리한다 — 예시 3개는 3개의 사례일 뿐 증명이 아니다.',
    followUps: [
      {
        id: 'E.PR.003.f1',
        dimension: 'generalization',
        prompt: '같은 방법으로 "연속하는 다섯 정수의 합"은 무엇의 배수임을 알 수 있나요?',
        choices: [{ text: '5의 배수 (합 = 5n)' }, { text: '3의 배수' }, { text: '15의 배수' }, { text: '아무 규칙 없음' }],
        answerIndex: 0,
        note: '(n−2)+(n−1)+n+(n+1)+(n+2) = 5n — 같은 구조가 홀수 개 연속합 전체로 일반화된다.',
      },
    ],
    estimatedSec: 200,
  },
  {
    id: 'E.PR.004',
    mode: 'PROOF',
    difficulty: 4,
    domain: 'GEO',
    requiredSkills: ['M1.GEO.ANG.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.85,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'explanation', evidenceFraction: 0.5 }], exclusionDimensions: ['novelTransfer', 'flexibility', 'reverseReasoning', 'generalization'] },
    noveltySignature: { representationType: '논증 선택', requiredSkillCombination: ['M1.GEO.ANG.01'], dominantReasoningMove: 'deductive-argument', structuralPattern: '맞꼭지각 상등의 연역', solutionFamily: ['common-supplement'] },
    stem: '두 직선이 만날 때 생기는 맞꼭지각이 항상 같은 이유로 완전한 것은?',
    choices: [
      { text: '두 맞꼭지각이 모두 같은 각과 합해 180°가 되므로 (∠a = 180° − ∠c = ∠b)' },
      { text: '그림을 그려서 재어 보면 항상 같게 나오므로', eliteTag: 'JUSTIFICATION' },
      { text: '두 직선이 대칭으로 생겼기 때문에', eliteTag: 'JUSTIFICATION' },
      { text: '맞꼭지각이라는 이름이 같다는 뜻이므로' },
    ],
    answerIndex: 0,
    hints: {
      A: '맞꼭지각 사이에 끼어 있는 각을 하나 지목해 보세요.',
      B: '이웃한 두 각은 직선 위에서 합이 180°예요(평각).',
      C: '∠a + ∠c = 180°, ∠b + ∠c = 180°.',
      D: '둘 다 180° − ∠c와 같아요.',
    },
    solution: '∠a와 ∠b가 공통 이웃각 ∠c와 각각 평각을 이루므로 ∠a = 180°−∠c = ∠b. 측정·대칭 인상은 근거가 아니다.',
    followUps: [],
    estimatedSec: 180,
  },
  {
    id: 'E.PR.005',
    mode: 'PROOF',
    difficulty: 5,
    domain: 'STA',
    requiredSkills: ['M1.STA.AVG.01', 'M1.STA.AVG.03'],
    noveltyScore: 0.6,
    reasoningValue: 0.9,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.3 }], exclusionDimensions: ['novelTransfer', 'flexibility', 'reverseReasoning'] },
    noveltySignature: { representationType: '논증 선택', requiredSkillCombination: ['M1.STA.AVG.01', 'M1.STA.AVG.03'], dominantReasoningMove: 'deductive-argument', structuralPattern: '평균 평행이동 성질의 증명', solutionFamily: ['symbolic-representation'] },
    stem: '"자료의 모든 값에 5를 더하면 평균도 정확히 5 커진다"의 증명으로 완전한 것은?',
    choices: [
      { text: '새 평균 = ((x₁+5)+⋯+(xₙ+5))/n = (x₁+⋯+xₙ)/n + 5n/n = 기존 평균 + 5' },
      { text: '3, 5, 7의 평균 5가 8, 10, 12에서 10이 되는 것으로 확인된다', eliteTag: 'JUSTIFICATION' },
      { text: '모두 커지니까 평균도 커지는 것이 당연하다', eliteTag: 'JUSTIFICATION' },
      { text: '평균은 가운데 값이므로 함께 5 이동한다' },
    ],
    answerIndex: 0,
    hints: {
      A: '"정확히 5"를 보이려면 커진다는 방향만으론 부족해요.',
      B: '새 자료의 평균을 식으로 통째로 적어 보세요.',
      C: '분자에서 +5가 n개 — 묶으면 5n.',
      D: '5n/n = 5가 따로 떨어져 나와요.',
    },
    solution: 'Σ(xᵢ+5)/n = Σxᵢ/n + 5n/n = 평균 + 5. "당연하다"는 방향만 말할 뿐 크기(정확히 5)를 보장하지 못한다.',
    followUps: [],
    estimatedSec: 210,
  },

  // ═════════════════════════ MULTIPLE_SOLUTION ═════════════════════════
  {
    id: 'E.MU.003',
    mode: 'MULTIPLE_SOLUTION',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.EQ.02', 'M1.ALG.EXP.02'],
    noveltyScore: 0.55,
    reasoningValue: 0.75,
    evidenceMap: { primaryDimension: 'strategySelection', secondaryDimensions: [{ dimension: 'flexibility', evidenceFraction: 0.6 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'novelTransfer'] },
    noveltySignature: { representationType: '방정식', requiredSkillCombination: ['M1.ALG.EQ.02', 'M1.ALG.EXP.02'], dominantReasoningMove: 'method-comparison', structuralPattern: '전개 vs 공통인수 나눗셈 선택', solutionFamily: ['expand-first', 'divide-first'] },
    stem: '방정식 3(x + 2) = 21을 푸세요. (전개하는 방법과 양변을 3으로 먼저 나누는 방법, 두 가지가 모두 가능합니다.)',
    choices: [{ text: 'x = 5' }, { text: 'x = 7', eliteTag: 'CARELESS' }, { text: 'x = 3' }, { text: 'x = 19/3' }],
    answerIndex: 0,
    hints: {
      A: '괄호를 꼭 풀어야만 할까요? 다른 길도 떠올려 보세요.',
      B: '방법 A: 전개 3x+6=21. 방법 B: 양변÷3 → x+2=7.',
      C: '어느 길이든 같은 답에 도착해야 해요.',
      D: 'x + 2 = 7 → x = 5.',
    },
    solution: '방법 A: 3x+6=21 → 3x=15 → x=5.',
    altSolution: '방법 B: 양변을 3으로 나눠 x+2=7 → x=5. 우변이 3의 배수일 때는 B가 계산이 짧다 — 방법 선택 자체가 실력이다.',
    followUps: [
      {
        id: 'E.MU.003.f1',
        dimension: 'flexibility',
        prompt: '4(x − 1) = 18을 풀 때, 양변을 4로 먼저 나누는 방법이 덜 편한 이유는?',
        choices: [{ text: '18이 4의 배수가 아니라 분수가 등장하기 때문' }, { text: '나누기는 방정식에서 금지이기 때문', eliteTag: 'STRATEGY' }, { text: '괄호는 항상 먼저 풀어야 하기 때문', eliteTag: 'STRATEGY' }, { text: '4가 짝수이기 때문' }],
        answerIndex: 0,
        note: '방법의 유불리는 수의 구조(배수 관계)에 달렸다 — 항상 같은 방법을 고집할 이유가 없다.',
      },
    ],
    estimatedSec: 150,
  },
  {
    id: 'E.MU.004',
    mode: 'MULTIPLE_SOLUTION',
    difficulty: 4,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.FRAC.01'],
    noveltyScore: 0.5,
    reasoningValue: 0.7,
    evidenceMap: { primaryDimension: 'flexibility', secondaryDimensions: [{ dimension: 'strategySelection', evidenceFraction: 0.6 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'novelTransfer'] },
    noveltySignature: { representationType: '분수식', requiredSkillCombination: ['M1.NUM.FRAC.01'], dominantReasoningMove: 'method-comparison', structuralPattern: '통분 기준(곱 vs 최소공배수) 비교', solutionFamily: ['lcm-denominator', 'product-denominator'] },
    stem: '다음을 계산하세요. (분모의 곱 12×4로 통분해도, 최소공배수 12로 통분해도 됩니다.)\n3/4 − 7/12',
    choices: [{ text: '1/6' }, { text: '−1/2', eliteTag: 'REPRESENTATION' }, { text: '1/3', eliteTag: 'CARELESS' }, { text: '5/12' }],
    answerIndex: 0,
    hints: {
      A: '두 분모를 같게 만드는 기준이 하나뿐일까요?',
      B: '최소공배수 12를 쓰면: 3/4 = 9/12.',
      C: '9/12 − 7/12 = 2/12.',
      D: '2/12를 약분하면?',
    },
    solution: '3/4 = 9/12 → 9/12 − 7/12 = 2/12 = 1/6.',
    altSolution: '분모 곱 48로 통분: 36/48 − 28/48 = 8/48 = 1/6. 결과는 같지만 약분 부담이 크다 — 최소공배수의 가치는 "덜 일하기".',
    followUps: [],
    estimatedSec: 120,
  },
  {
    id: 'E.MU.005',
    mode: 'MULTIPLE_SOLUTION',
    difficulty: 4,
    domain: 'FUN',
    requiredSkills: ['M1.FUN.AREA.01', 'M1.FUN.COORD.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.75,
    evidenceMap: { primaryDimension: 'flexibility', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.4 }], exclusionDimensions: ['generalization', 'reverseReasoning', 'justification'] },
    noveltySignature: { representationType: '좌표', requiredSkillCombination: ['M1.FUN.AREA.01', 'M1.FUN.COORD.01'], dominantReasoningMove: 'method-comparison', structuralPattern: '삼각형 넓이의 직접 공식 vs 둘러싸기', solutionFamily: ['base-height', 'bounding-rectangle'] },
    stem: '세 점 O(0, 0), A(6, 0), B(6, 4)를 꼭짓점으로 하는 삼각형 OAB의 넓이를 구하세요.',
    choices: [{ text: '12' }, { text: '24', eliteTag: 'STRATEGY' }, { text: '10' }, { text: '48' }],
    answerIndex: 0,
    hints: {
      A: '밑변과 높이가 좌표에서 바로 보이나요?',
      B: '방법 A: OA를 밑변(6), 높이 4. 방법 B: 6×4 직사각형의 절반.',
      C: '6 × 4 ÷ 2.',
      D: '= 12.',
    },
    solution: '방법 A: 밑변 OA = 6, 높이 = B의 y좌표 4 → 6×4÷2 = 12.',
    altSolution: '방법 B: O, A, B에 (0,4)를 더한 직사각형(넓이 24)을 대각선 OB가 정확히 반으로 가른다 → 12. 좌표 도형은 "둘러싸기"가 강력한 대안 전략.',
    followUps: [],
    estimatedSec: 140,
  },

  // ═════════════════════════ ERROR_ANALYSIS ═════════════════════════
  {
    id: 'E.EA.003',
    mode: 'ERROR_ANALYSIS',
    difficulty: 3,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.FRAC.01'],
    noveltyScore: 0.5,
    reasoningValue: 0.75,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'explanation', evidenceFraction: 0.5 }], exclusionDimensions: ['novelTransfer', 'reverseReasoning', 'flexibility'] },
    noveltySignature: { representationType: '오답 풀이', requiredSkillCombination: ['M1.NUM.FRAC.01'], dominantReasoningMove: 'error-detection', structuralPattern: '분모 합산 오류 위치 식별', solutionFamily: ['step-audit'] },
    stem: '어느 학생의 풀이입니다.\n[1단계] 2/3 + 1/6 = 3/9\n[2단계] 3/9 = 1/3\n어디에서 처음 잘못되었을까요?',
    choices: [
      { text: '1단계 — 분자끼리, 분모끼리 그냥 더했다 (통분 필요)' },
      { text: '2단계 — 약분이 틀렸다', eliteTag: 'JUSTIFICATION' },
      { text: '두 단계 모두 옳고 답만 틀렸다' },
      { text: '잘못된 곳이 없다', eliteTag: 'CARELESS' },
    ],
    answerIndex: 0,
    hints: {
      A: '각 단계를 따로 검사해요 — 뒤 단계부터가 아니라 앞에서부터.',
      B: '분수 덧셈에서 분모끼리 더해도 될까요?',
      C: '2/3 = 4/6이므로 옳은 답은 4/6 + 1/6 = 5/6.',
      D: '2단계의 약분(3/9=1/3) 자체는 옳은 계산이에요 — 문제는 1단계.',
    },
    solution: '오류는 1단계(분모 합산). 2단계 약분은 그 자체로는 옳다 — "처음 잘못된 곳"을 찾으려면 단계별 감사가 필요하다. 옳은 답: 5/6.',
    followUps: [
      {
        id: 'E.EA.003.f1',
        dimension: 'explanation',
        prompt: '이 학생에게 해 줄 가장 도움이 되는 한마디는?',
        choices: [{ text: '"분모가 다르면 단위가 다른 것 — 같은 단위(공통분모)로 바꾼 뒤 분자만 더해"' }, { text: '"답이 틀렸으니 다시 풀어 봐"', eliteTag: 'JUSTIFICATION' }, { text: '"약분을 조심해"' }, { text: '"분수는 어려우니 소수로 바꿔서 풀어"' }],
        answerIndex: 0,
        note: '오류의 기제(단위 불일치)를 짚는 피드백이 재발을 막는다 — "다시 풀어"는 정보가 없다.',
      },
    ],
    estimatedSec: 150,
  },
  {
    id: 'E.EA.004',
    mode: 'ERROR_ANALYSIS',
    difficulty: 4,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.VAL.02', 'M1.NUM.POW.01'],
    noveltyScore: 0.55,
    reasoningValue: 0.8,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.4 }], exclusionDimensions: ['novelTransfer', 'reverseReasoning', 'flexibility'] },
    noveltySignature: { representationType: '오답 풀이', requiredSkillCombination: ['M1.ALG.VAL.02', 'M1.NUM.POW.01'], dominantReasoningMove: 'error-detection', structuralPattern: '−x²/(−x)² 범위 혼동 식별', solutionFamily: ['notation-scope'] },
    stem: '어느 학생이 "x = −3일 때 −x²의 값"을 9라고 답했습니다. 이 학생의 생각에서 잘못된 지점은?',
    choices: [
      { text: '−x²은 −(x²) = −9인데, (−x)² = 9로 해석했다 (거듭제곱이 부호보다 먼저)' },
      { text: '(−3)² 계산 자체를 틀렸다', eliteTag: 'JUSTIFICATION' },
      { text: '대입할 때 괄호를 씌우지 않았다', eliteTag: 'REPRESENTATION' },
      { text: '잘못 없음 — 9가 맞다', eliteTag: 'CARELESS' },
    ],
    answerIndex: 0,
    hints: {
      A: '9라는 답은 어떤 식을 계산하면 나올까요?',
      B: '−x²과 (−x)² — 기호는 비슷하지만 계산 순서가 달라요.',
      C: '거듭제곱이 −부호보다 먼저: −x² = −(x²).',
      D: 'x=−3이면 x²=9, 그래서 −x² = −9.',
    },
    solution: '9는 (−x)²의 값이다. −x²은 −(x²) = −9. 오류는 "계산 실수"가 아니라 표기의 적용 범위(scope) 해석 — 어떤 잘못인지 정확히 지목하는 것이 교정의 시작.',
    followUps: [],
    estimatedSec: 160,
  },
  {
    id: 'E.EA.005',
    mode: 'ERROR_ANALYSIS',
    difficulty: 4,
    domain: 'STA',
    requiredSkills: ['M1.STA.REL.01', 'M1.STA.REL.02'],
    noveltyScore: 0.55,
    reasoningValue: 0.75,
    evidenceMap: { primaryDimension: 'justification', secondaryDimensions: [{ dimension: 'integration', evidenceFraction: 0.3 }], exclusionDimensions: ['novelTransfer', 'reverseReasoning', 'flexibility'] },
    noveltySignature: { representationType: '오답 표', requiredSkillCombination: ['M1.STA.REL.01', 'M1.STA.REL.02'], dominantReasoningMove: 'error-detection', structuralPattern: '상대도수 합 불변량으로 오류 계급 색출', solutionFamily: ['invariant-check'] },
    stem: '전체 40명 조사표에서 학생이 적은 상대도수가 다음과 같습니다.\n계급A(도수 8): 0.2 | 계급B(도수 12): 0.3 | 계급C(도수 4): 0.1 | 계급D(도수 16): 0.5\n합이 1.1이 되어 이상합니다. 어느 계급의 상대도수가 잘못되었을까요?',
    choices: [
      { text: '계급D — 16/40 = 0.4인데 0.5로 적었다' },
      { text: '계급A — 8/40은 0.25이다', eliteTag: 'CARELESS' },
      { text: '계급B — 12/40은 0.25이다' },
      { text: '잘못 없음 — 상대도수 합은 1이 아니어도 된다', eliteTag: 'JUSTIFICATION' },
    ],
    answerIndex: 0,
    hints: {
      A: '상대도수 전체의 합은 항상 얼마여야 할까요?',
      B: '합이 1보다 0.1 크다 — 0.1만큼 부풀려진 계급을 찾아요.',
      C: '각 계급을 도수÷40으로 직접 검산해요.',
      D: '16 ÷ 40 = 0.4 ≠ 0.5.',
    },
    solution: '불변량(합=1)이 깨진 크기 0.1을 단서로: 16/40 = 0.4이므로 계급D가 0.1 부풀려졌다. A(8/40=0.2), B(12/40=0.3), C(4/40=0.1)는 옳다.',
    followUps: [],
    estimatedSec: 170,
  },

  // ═════════════════════════ OPEN_ENDED (PART 15-17) ═════════════════════════
  // 구조: 결정적 판별(정답 보기) + rubric(문제별 기준) + 근거 후속(justification).
  // 정답만으로 explanation/justification을 올리지 않는다(PART 18) — 배제 차원으로 강제.
  {
    id: 'E.OE.001',
    mode: 'OPEN_ENDED',
    difficulty: 4,
    domain: 'NUM',
    requiredSkills: ['M1.NUM.POW.01', 'M1.NUM.SIGN.02'],
    noveltyScore: 0.75,
    reasoningValue: 0.9,
    evidenceMap: { primaryDimension: 'strategySelection', secondaryDimensions: [{ dimension: 'generalization', evidenceFraction: 0.4 }], exclusionDimensions: ['justification', 'explanation', 'reverseReasoning'] },
    noveltySignature: { representationType: '주장 평가', requiredSkillCombination: ['M1.NUM.POW.01', 'M1.NUM.SIGN.02'], dominantReasoningMove: 'claim-evaluation', structuralPattern: '(−1)ⁿ 이웃 항 상쇄의 항상성 판정', solutionFamily: ['parity-argument'] },
    rubric: {
      criteria: [
        '0 — 판단 근거 없음 (추측)',
        '1 — 몇 개의 n으로 확인만 함 (부분 관찰)',
        '2 — 홀짝이 핵심임을 알지만 "왜 모든 n에서"는 설명 못 함',
        '3 — 연속 지수가 홀짝 하나씩임을 근거로 항상성을 설명',
        '4 — (−1)ⁿ과 (−1)ⁿ⁺¹이 항상 덧셈 역원임을 일반 구조로 진술',
      ],
      deterministicChecks: ['본문 정답 선택(항상 성립)', '근거 후속에서 구조적 논거 식별'],
    },
    stem: '[열린 탐구] 주장: "n이 어떤 자연수든 (−1)ⁿ + (−1)ⁿ⁺¹의 값은 항상 0이다."\n이 주장은 항상 성립할까요?',
    choices: [
      { text: '항상 성립한다 — n과 n+1 중 하나는 홀수, 하나는 짝수라 두 항이 +1과 −1로 짝을 이룬다' },
      { text: 'n이 짝수일 때만 성립한다', eliteTag: 'GENERALIZATION' },
      { text: 'n이 홀수일 때만 성립한다', eliteTag: 'GENERALIZATION' },
      { text: '성립하지 않는 n이 적어도 하나 있다' },
    ],
    answerIndex: 0,
    hints: {
      A: 'n에 몇 개의 값을 넣어 관찰해 보세요 — 그 다음 "왜"를 물어요.',
      B: 'n과 n+1의 홀짝은 어떤 관계인가요?',
      C: '이웃한 자연수는 항상 홀수 하나 + 짝수 하나.',
      D: '그래서 두 항은 항상 (+1)과 (−1) — 순서만 다를 뿐.',
    },
    solution: 'n, n+1은 항상 홀·짝 하나씩이므로 (−1)ⁿ과 (−1)ⁿ⁺¹은 항상 {+1, −1}. 합은 모든 n에서 0 — "항상"의 근거는 사례가 아니라 홀짝 구조다.',
    followUps: [
      {
        id: 'E.OE.001.f1',
        dimension: 'justification',
        prompt: '"항상 성립"의 근거로 가장 완전한 것은?',
        choices: [
          { text: 'n=1,2,3에서 모두 0이 나왔기 때문', eliteTag: 'JUSTIFICATION' },
          { text: '이웃한 두 지수는 홀짝이 반드시 갈리므로 두 항이 항상 +1, −1 하나씩이기 때문' },
          { text: '(−1)은 특별한 수라서 더하면 항상 0이 되기 때문', eliteTag: 'JUSTIFICATION' },
          { text: '지수가 커질수록 값이 작아지기 때문' },
        ],
        answerIndex: 1,
        note: '사례 확인(rubric 1)과 구조 논거(rubric 3-4)의 차이를 가르는 문항.',
      },
    ],
    estimatedSec: 200,
  },
  {
    id: 'E.OE.002',
    mode: 'OPEN_ENDED',
    difficulty: 5,
    domain: 'ALG',
    requiredSkills: ['M1.ALG.EQ.BOTH.01', 'M1.ALG.EQ.01'],
    noveltyScore: 0.8,
    reasoningValue: 0.95,
    evidenceMap: { primaryDimension: 'strategySelection', secondaryDimensions: [{ dimension: 'flexibility', evidenceFraction: 0.4 }], exclusionDimensions: ['justification', 'explanation', 'reverseReasoning'] },
    noveltySignature: { representationType: '주장 평가', requiredSkillCombination: ['M1.ALG.EQ.BOTH.01', 'M1.ALG.EQ.01'], dominantReasoningMove: 'case-split', structuralPattern: '일차방정식 해 개수의 완전 분류', solutionFamily: ['case-analysis'] },
    rubric: {
      criteria: [
        '0 — 근거 없는 판단',
        '1 — 반례 하나(해 없음 또는 항등식)만 발견',
        '2 — 두 종류의 예외를 알지만 조건(a=c)으로 묶지 못함',
        '3 — a≠c / a=c,b≠d / a=c,b=d 세 경우를 완전 분류',
        '4 — 분류가 "x항이 소거되는가"라는 구조에서 나옴을 진술',
      ],
      deterministicChecks: ['본문에서 완전 분류 보기 선택', '후속에서 반례 구성 식별'],
    },
    stem: '[열린 탐구] 주장: "ax + b = cx + d 꼴의 방정식은 항상 해가 정확히 하나다."\n가장 정확한 판단은?',
    choices: [
      { text: 'a ≠ c면 해가 하나, a = c면 (b ≠ d일 때) 해가 없거나 (b = d일 때) 모든 수가 해다' },
      { text: '주장이 옳다 — 일차방정식이므로 항상 하나다', eliteTag: 'GENERALIZATION' },
      { text: '해가 없을 수는 있어도 무수히 많을 수는 없다', eliteTag: 'STRATEGY' },
      { text: 'b = d일 때만 해가 존재한다' },
    ],
    answerIndex: 0,
    hints: {
      A: '"항상"이 붙은 주장은 반례 사냥부터 — 특별한 a, c를 골라 보세요.',
      B: 'a = c로 만들면 x항에 무슨 일이 생기나요?',
      C: '2x+1 = 2x+3 (해 없음), 2x+1 = 2x+1 (모든 수가 해).',
      D: '그래서 경우가 세 갈래로 갈라져요.',
    },
    solution: '(a−c)x = d−b. a≠c → x = (d−b)/(a−c) 하나. a=c → 좌변 0: b≠d면 모순(해 없음), b=d면 항등식(모든 수). 완전 분류가 답이다.',
    followUps: [
      {
        id: 'E.OE.002.f1',
        dimension: 'justification',
        prompt: '"해가 정확히 하나"라는 주장을 무너뜨리는 반례로 옳은 것은?',
        choices: [
          { text: '3x + 1 = 3x + 5 (어떤 x도 만족 못 함)' },
          { text: 'x + 1 = 4 (해가 하나뿐)', eliteTag: 'JUSTIFICATION' },
          { text: '2x = 6 (해가 3 하나)', eliteTag: 'JUSTIFICATION' },
          { text: 'x² = 4 (일차가 아님)' },
        ],
        answerIndex: 0,
        note: '반례는 주장의 형식(ax+b=cx+d)에 맞으면서 결론(해 하나)을 깨야 한다 — x²=4는 형식 위반이라 반례가 아니다.',
      },
    ],
    estimatedSec: 240,
  },
  {
    id: 'E.OE.003',
    mode: 'OPEN_ENDED',
    difficulty: 4,
    domain: 'GEO',
    requiredSkills: ['M1.GEO.POLY.01', 'M1.GEO.POLY.02'],
    noveltyScore: 0.75,
    reasoningValue: 0.9,
    evidenceMap: { primaryDimension: 'strategySelection', secondaryDimensions: [{ dimension: 'reverseReasoning', evidenceFraction: 0.4 }], exclusionDimensions: ['justification', 'explanation', 'flexibility'] },
    noveltySignature: { representationType: '존재성 탐구', requiredSkillCombination: ['M1.GEO.POLY.01', 'M1.GEO.POLY.02'], dominantReasoningMove: 'existence-check', structuralPattern: '조건을 만족하는 정다각형의 존재 판정', solutionFamily: ['equation-setup', 'integrality-argument'] },
    rubric: {
      criteria: [
        '0 — 판단 근거 없음',
        '1 — 몇 개의 정다각형을 대입해 봄',
        '2 — 식은 세웠으나 n의 정수성 조건을 못 봄',
        '3 — 식에서 n = 4.5를 얻고 정수가 아님을 근거로 부정',
        '4 — 존재 문제를 "방정식의 자연수 해 존재"로 번역하는 구조를 진술',
      ],
      deterministicChecks: ['본문 정답 선택(존재하지 않음 + 근거)'],
    },
    stem: '[열린 탐구] 한 내각의 크기가 정확히 100°인 정다각형이 존재할까요? 가능한 모든 경우를 따져 보세요.',
    choices: [
      { text: '존재하지 않는다 — 180(n−2)/n = 100을 풀면 n = 4.5로 자연수가 아니다' },
      { text: '정오각형이 그렇다 (내각 100°)', eliteTag: 'CARELESS' },
      { text: '정구각형이 그렇다', eliteTag: 'STRATEGY' },
      { text: '무수히 많은 정다각형이 가능하다' },
    ],
    answerIndex: 0,
    hints: {
      A: '"존재하는가"를 식으로 번역해 보세요.',
      B: '정n각형 한 내각 = 180(n−2)/n. 이것이 100이 되는 n을 찾는 문제로 바뀌어요.',
      C: '180n − 360 = 100n → 80n = 360.',
      D: 'n = 4.5 — 꼭짓점이 4.5개인 다각형이 있을까요?',
    },
    solution: '180(n−2)/n = 100 → n = 4.5. n은 자연수여야 하므로 존재하지 않는다. "모든 경우 탐색"이 방정식 하나 + 정수성 조건으로 압축된다.',
    followUps: [
      {
        id: 'E.OE.003.f1',
        dimension: 'generalization',
        prompt: '그렇다면 정다각형의 한 내각이 될 수 있는 각도의 특징은?',
        choices: [
          { text: '180(n−2)/n (n≥3 자연수) 꼴의 값만 가능 — 60°, 90°, 108°, 120°, …' },
          { text: '60°와 180° 사이의 모든 각도가 가능하다', eliteTag: 'GENERALIZATION' },
          { text: '짝수 각도만 가능하다' },
          { text: '90°의 배수만 가능하다' },
        ],
        answerIndex: 0,
        note: '한 존재 판정을 "가능한 값 전체의 목록"으로 일반화 — 열린 탐구의 다음 질문.',
      },
    ],
    estimatedSec: 220,
  },
  {
    id: 'E.OE.004',
    mode: 'OPEN_ENDED',
    difficulty: 4,
    domain: 'FUN',
    requiredSkills: ['M1.FUN.PROP.03', 'M1.FUN.PROP.05'],
    noveltyScore: 0.7,
    reasoningValue: 0.85,
    evidenceMap: { primaryDimension: 'flexibility', secondaryDimensions: [{ dimension: 'representation', evidenceFraction: 0.4 }], exclusionDimensions: ['justification', 'explanation', 'reverseReasoning'] },
    noveltySignature: { representationType: '조건 변형', requiredSkillCombination: ['M1.FUN.PROP.03', 'M1.FUN.PROP.05'], dominantReasoningMove: 'condition-perturbation', structuralPattern: '반비례 상수 변경의 전역 효과 추론', solutionFamily: ['pointwise-scaling'] },
    rubric: {
      criteria: [
        '0 — 근거 없는 판단',
        '1 — 한 점에서만 확인',
        '2 — 여러 점에서 2배임을 확인하나 이유를 못 댐',
        '3 — y = a/x 구조에서 a 2배 → 각 x의 y가 2배임을 설명',
        '4 — "x축 방향은 불변, y축 방향 2배 늘이기"라는 그래프 변환으로 진술',
      ],
      deterministicChecks: ['본문 정답 선택(각 점의 y가 2배)'],
    },
    stem: '[조건 바꾸기] 반비례 y = a/x (a > 0)에서 a를 2배로 바꾸면, 그래프 위 각 점에는 무슨 일이 일어날까요?',
    choices: [
      { text: '같은 x에서 y값이 모두 2배가 된다 (그래프가 위로 "늘어난다")' },
      { text: '그래프가 오른쪽으로 2만큼 이동한다', eliteTag: 'REPRESENTATION' },
      { text: 'y값이 모두 2만큼 커진다', eliteTag: 'REPRESENTATION' },
      { text: '아무 변화 없다 — 반비례는 모양이 하나뿐이다' },
    ],
    answerIndex: 0,
    hints: {
      A: '한 점을 골라 실험해 보세요 — 예: x = 2.',
      B: 'y = 6/x과 y = 12/x에서 x=2의 y는 각각?',
      C: '3과 6 — 두 배. 다른 x에서도 그럴까요?',
      D: 'y = 2a/x = 2·(a/x) — 모든 x에서 y가 2배.',
    },
    solution: '2a/x = 2(a/x)이므로 같은 x에서 y가 정확히 2배. "2만큼 더하기"(평행이동)와 "2배 하기"(늘이기)는 완전히 다른 변화다.',
    followUps: [],
    estimatedSec: 190,
  },
  {
    id: 'E.OE.005',
    mode: 'OPEN_ENDED',
    difficulty: 5,
    domain: 'STA',
    requiredSkills: ['M1.STA.AVG.01', 'M1.STA.AVG.03'],
    noveltyScore: 0.8,
    reasoningValue: 0.95,
    evidenceMap: { primaryDimension: 'strategySelection', secondaryDimensions: [{ dimension: 'integration', evidenceFraction: 0.3 }], exclusionDimensions: ['justification', 'explanation', 'reverseReasoning'] },
    noveltySignature: { representationType: '주장 평가', requiredSkillCombination: ['M1.STA.AVG.01', 'M1.STA.AVG.03'], dominantReasoningMove: 'claim-evaluation', structuralPattern: '합병 평균의 위치(두 평균 사이) 판정', solutionFamily: ['weighted-average-bound'] },
    rubric: {
      criteria: [
        '0 — 근거 없는 판단',
        '1 — 한 사례로만 확인',
        '2 — "사이에 온다"는 직관은 있으나 근거 없음',
        '3 — 총합/총인원 구조로 합친 평균이 두 평균 사이임을 설명',
        '4 — 가중 평균으로서 인원 비에 따라 어느 쪽에 가까워지는지까지 진술',
      ],
      deterministicChecks: ['본문 정답 선택(참 + 사이 근거)'],
    },
    stem: '[열린 탐구] 주장: "평균 70점인 모둠과 평균 80점인 모둠을 합치면, 전체 평균은 80점보다 클 수 없다."\n이 주장에 대한 가장 정확한 판단은?',
    choices: [
      { text: '참 — 합친 평균은 항상 두 평균 사이(70 이상 80 이하)에 있다' },
      { text: '거짓 — 두 모둠이 모두 크면 80을 넘을 수 있다', eliteTag: 'STRATEGY' },
      { text: '참이지만, 합친 평균은 항상 정확히 75다', eliteTag: 'GENERALIZATION' },
      { text: '인원수를 모르면 판단할 수 없다' },
    ],
    answerIndex: 0,
    hints: {
      A: '극단적인 경우(한쪽 인원이 아주 많음)를 상상해 보세요.',
      B: '합친 평균 = (총점의 합) ÷ (인원의 합) — 각 모둠 총점은 평균×인원.',
      C: '(70m + 80n)/(m+n) 꼴 — 이 값이 80을 넘으려면?',
      D: '70m + 80n ≤ 80m + 80n — 항상 80(m+n) 이하예요.',
    },
    solution: '(70m+80n)/(m+n) ≤ 80 ⇔ 70m ≤ 80m (항상 참). 같은 논리로 70 이상. 인원 비에 따라 사이 어디든 갈 수 있지만(75 고정 아님) 밖으로는 못 나간다.',
    followUps: [
      {
        id: 'E.OE.005.f1',
        dimension: 'justification',
        prompt: '"정확히 75가 된다"가 틀린 이유를 보이는 반례는?',
        choices: [
          { text: '70점 모둠 1명 + 80점 모둠 9명 → 평균 79점' },
          { text: '두 모둠 인원이 같은 경우 → 평균 75점', eliteTag: 'JUSTIFICATION' },
          { text: '모든 학생이 75점인 경우', eliteTag: 'JUSTIFICATION' },
          { text: '반례가 없다 — 75가 맞다' },
        ],
        answerIndex: 0,
        note: '(70+720)/10 = 79 ≠ 75. 인원이 같을 때의 75는 반례가 아니라 특수 사례다.',
      },
    ],
    estimatedSec: 260,
  },
];
